const axios = require('axios');

let daveplug = async (m, { dave, text, reply, quoted, command, prefix }) => {
    try {
        // Extract prompt from text or quoted message
        const used = (text || '').split(/\s+/)[0] || command;
        const args = text ? text.slice(used.length).trim() : '';
        const quotedText = quoted?.text || '';
        const input = args || quotedText;

        if (!input) {
            return await reply(`❌ Please provide a prompt.\n\n💡 Example: ${prefix + command} anime girl with short blue hair\n💡 Or reply to a message with ${prefix + command}`);
        }

        // Add processing reaction
        await dave.sendMessage(m.chat, {
            react: { text: '🎬', key: m.key }
        });

        const apiUrl = `https://okatsu-rolezapiiz.vercel.app/ai/txt2video?text=${encodeURIComponent(input)}`;
        const { data } = await axios.get(apiUrl, { 
            timeout: 60000, 
            headers: { 'user-agent': 'Mozilla/5.0' } 
        });

        const videoUrl = data?.videoUrl || data?.result || data?.data?.videoUrl;
        if (!videoUrl) {
            throw new Error('No video URL in API response');
        }

        // Send the generated video
        await dave.sendMessage(m.chat, {
            video: { url: videoUrl },
            mimetype: 'video/mp4',
            caption: `🎬 *Sora AI Video*\n\n📝 *Prompt:* ${input}\n\n✨ Generated by DaveAI`
        }, { quoted: m });

        // Add success reaction
        await dave.sendMessage(m.chat, {
            react: { text: '✅', key: m.key }
        });

    } catch (error) {
        console.error('Sora Command Error:', error);
        
        // Add error reaction
        await dave.sendMessage(m.chat, {
            react: { text: '❌', key: m.key }
        });
        
        await reply('❌ Failed to generate video. The service might be busy or the prompt was rejected. Try again later with a different prompt.');
    }
};

daveplug.help = ['sora'];
daveplug.tags = ['ai'];
daveplug.command = ['sora', 'soravideo', 'txt2video'];

module.exports = daveplug;